# Generated by Django 5.1.3 on 2024-11-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('node', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('ext_no', models.CharField(max_length=50)),
                ('port_ip', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('power_broker_id', models.CharField(max_length=50)),
                ('applied_rating_id', models.CharField(max_length=50)),
                ('user_creation_date', models.DateField()),
                ('suspended_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
